name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests requests-mock

    - name: Run FastAPI app
      run: |
        cd src
        . venv/bin/activate
        uvicorn src.main:app --host 0.0.0.0 --port 8000 &
      env:
        DATABASE_URL: "sqlite:///./tests/test.db"

    - name: Run Streamlit app
      run: |
        cd src
        . venv/bin/activate
        streamlit run src/app.py &
      env:
        DATABASE_URL: "sqlite:///./tests/test.db"

    - name: Wait for services to be ready
      run: |
        sudo apt-get install -y wait-for-it
        wait-for-it localhost:8000 --timeout=60
        wait-for-it localhost:8501 --timeout=60

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest tests/
